# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Serverless TypeScript Lambda API built on AWS

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Parameters section
Parameters:
  RootDomainName:
    Type: String
    Description: Root domain name for the API (e.g., example.com)
  SubDomainName:
    Type: String
    Description: Subdomain the api is on
    Default: "api"
  AdminUsername:
    Type: String
    Description: Admin username (without domain, will be used as username@RootDomainName)
    Default: admin
  AllowedClientOrigins:
    Type: CommaDelimitedList
    Description: "Comma-separated allowed CORS origins (e.g., https://example.com,https://second.com,http://localhost:5173)"
    Default: "http://localhost:5173"
  VertexAiApiKey:
    Type: String
    Description: "Vertex AI API Key"
    NoEcho: true
  GoogleVertexProject:
    Type: String
    Description: "Google Vertex Project ID"
  GoogleVertexLocation:
    Type: String
    Description: "Google Vertex Location"
    Default: "us-central1"
  GoogleApplicationCredentials:
    Type: String
    Description: "Path to Google Application Credentials file"
    Default: "./google-credentials.json"

# Globals section for shared function and API Gateway configuration
Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Timeout: 30
    Environment:
      Variables:
        ALLOWED_ORIGINS: !Join [',', !Ref AllowedClientOrigins]
        BASE_URL: !Sub 'https://${SubDomainName}.${RootDomainName}'
        USER_POOL_CLIENT_ID: !Ref UserPoolClient
        USER_POOL_ID: !Ref UserPool
        VERTEX_AI_API_KEY: !Ref VertexAiApiKey
        GOOGLE_VERTEX_PROJECT: !Ref GoogleVertexProject
        GOOGLE_VERTEX_LOCATION: !Ref GoogleVertexLocation
        GOOGLE_APPLICATION_CREDENTIALS: !Ref GoogleApplicationCredentials

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # HTTP API (no API Gateway authorizer; handlers enforce Basic/Bearer)
  LambdaHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefaultRouteSettings:
        ThrottlingBurstLimit: 1000
        ThrottlingRateLimit: 500
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Authorization
          - Content-Type
          - Cookie
          - X-Requested-With
        AllowOrigins: !Ref AllowedClientOrigins
        AllowCredentials: true

  # Cognito User Pool Client (required for API Gateway integration)
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: lambda-api-client
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  # Admin user for the User Pool
  AdminUser:
    Type: AWS::Cognito::UserPoolUser
    DependsOn: UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      Username: !Sub '${AdminUsername}@${RootDomainName}'
      MessageAction: SUPPRESS
      UserAttributes:
        - Name: email
          Value: !Sub '${AdminUsername}@${RootDomainName}'
        - Name: email_verified
          Value: 'true'
      DesiredDeliveryMediums: []
      ForceAliasCreation: false

  # API ENDPOINTS
  apiAuthedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/api/authed.authedHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaHttpApi
            Path: /api/authed
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/api/authed.ts

  apiUnauthedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/api/unauthed.unauthedHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaHttpApi
            Path: /api/unauthed
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/api/unauthed.ts

  # AUTH ENDPOINTS

  authLogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/auth/logout.handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaHttpApi
            Path: /auth/logout
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/logout.ts

  authLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/auth/login.handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaHttpApi
            Path: /auth/login
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/login.ts

  authTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/auth/token.handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaHttpApi
            Path: /auth/token
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/token.ts

  # END OF AUTH API ENDPOINTS

  # ERROR PAGES

  errorPagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/errors/index.errorHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaHttpApi
            Path: /errors/{errorCode}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        Loader:
          - .html=text
        EntryPoints:
          - src/handlers/errors/index.ts

  # END OF ERROR PAGES

  # User pool for auth (cognito)
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    Properties:
      UserPoolName: lambda-api-UserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true

      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false



Outputs:
  HttpApiId:
    Description: "HTTP API ID"
    Value: !Ref LambdaHttpApi
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient
